# Generated by Django 6.0.4 on 2026-04-24 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_type', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra_large', 'Extra Large')], max_length=20)),
                ('category', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('refrigerated', 'Refrigerated'), ('flatbed', 'Flatbed')], max_length=20)),
                ('capacity', models.PositiveIntegerField(help_text='Truck capacity in tons.')),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('big', 'Big')], help_text='Truck size — affects the final price.', max_length=10)),
                ('departure_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('departure_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('arrival_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('arrival_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('distance', models.DecimalField(decimal_places=2, help_text='Distance in kilometres.', max_digits=8)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('workers', models.PositiveSmallIntegerField(default=0, help_text='Number of additional workers (0–5).')),
                ('price', models.DecimalField(decimal_places=2, help_text='Calculated price in DZD.', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_employee', models.ForeignKey(blank=True, help_text='The employee who accepted this mission. Null until accepted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_as_employee', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(help_text='The client who requested this mission.', on_delete=django.db.models.deletion.CASCADE, related_name='missions_as_client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'ordering': ['-created_at'],
            },
        ),
    ]
