# Generated by Django 6.0.4 on 2026-04-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='phone_number',
            field=models.CharField(default='0655151371', help_text='Client contact number — must start with 05, 06, or 07 and be 10 digits.', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='shipment_type',
            field=models.CharField(default='0000000000', help_text='Kind of goods being transported (e.g. house_moving, commercial_goods).', max_length=50),
            preserve_default=False,
        ),
    ]
