# Generated by Django 6.0.4 on 2026-04-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_mission_phone_number_mission_shipment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20),
        ),
    ]
